### ISSUE TITLE
오늘 할 일

### ISSUE THREAD

**Issue by gwonhan** [panghunJO/HitechProject1#19]
### 👀 관련 이슈

관리자- 등록 삭제 조회 수정 만들기 crud

### ✨ 작업한 내용

- [x] 관리자 직원 메인페이지 
- [x] 모든 페이지 로고
- [x] 모든 헤더 경로 설정
- [x] 수리예약 수정
- [x] 삭제
- [ ] 관리자 계정 수정 
- [ ] 삭제
- [ ] 작업 조회
- [ ] 수정
- [ ] 삭제
- [x] 직원 계정 수정
- [ ] 삭제
- [x] 사용자 이름 마이페이지 
- [ ] 로그아웃
- [ ] 캘린더 찾기
- [ ] alert 창 만들기
### 📷 스크린샷 또는 GIF
|기능|스크린샷|
|:--:|:--:|
|||

**Comment by ggeunn** [comment]
- [ ] 작업에 진행상황 추가
- [ ] 계정에 주소 추가

**Comment by ggeunn** [comment]
계정에 주소 추가해야됨

**Comment by sunnyskylove** [comment]
### [계정] 변경사항 
- UserDTO 추가 : address, department (column도 추가) / phone, email

**Comment by sunnyskylove** [comment]
작업할 내용 : 캘린더 찾기,  alert 창 만들기 추가함
