### ISSUE TITLE
수리 예약 추가 기능

### ISSUE THREAD

**Issue by ggeunn** [panghunJO/HitechProject1#98]
### 👀 관련 이슈
수리 예약 추가 기능

### ✨ 작업한 내용

- [x]  수리 예약 시간 입력 받기
- [x]  수리 예약 차량 정보 페이지
- [x]  작업 ,  수리 예약 등록 , 수리 예약 조회 날짜시간 타입 맞추기
- [x]  날짜 시간 등록 페이지

### 📷 스크린샷 또는 GIF
|기능|스크린샷|
|:--:|:--:|
|||

**Comment by sunnyskylove** [comment]
(수리)예약 > 차량 등록 페이지 완료
